#!/usr/bin/env node
/* Preconnect home page — test suite.   node tests/run_all.js   (exit code 0 = all passed) */
const fs=require('fs'),path=require('path'),vm=require('vm');const {boot}=require('./hub_mock.js');
let failed=0,n=0;function report(name,ok,detail=''){n++;if(!ok)failed++;console.log(`${ok?'PASS':'FAIL'}  ${name}${detail?'  — '+detail:''}`);}
const html=fs.readFileSync(path.join(__dirname,'..','index.html'),'utf8'),sw=fs.readFileSync(path.join(__dirname,'..','sw.js'),'utf8');
const FIX=JSON.parse(fs.readFileSync(path.join(__dirname,'fixture.json'),'utf8'));
try{new vm.Script(html.split('<script>')[1].split('</script>')[0]);report('script compiles',true);}catch(e){report('script compiles',false,e.message);}
{const ver=(html.match(/APP_VERSION='([^']+)'/)||[])[1],cache=(sw.match(/CACHE = '([^']+)'/)||[])[1];report('offline cache matches app version',cache===`preconnect-v${ver}`,`${ver} / ${cache}`);}
{const m=sw.match(/const ownFile = (.+);/);const own=new Function('url','return '+m[1]+';');const T=p=>own({pathname:p});
 report('offline helper handles only its own root files (and its fonts folder)',T('/')&&T('/index.html')&&T('/icon-192.png')&&T('/fonts/atkinson-hyperlegible-latin-400-normal.woff2')&&['/charge-the-line/','/patient-contact/index.html','/bleed-control/','/bls-ready/sw.js','/upwind/','/upwind/index.html','/next-module/'].every(p=>!T(p)));
 report('offline helper only clears its own old caches',/k\.startsWith\('preconnect-v'\)/.test(sw));}
{const {api}=boot();report('links to all five module folders (relative paths)',['charge-the-line/','patient-contact/','bleed-control/','bls-ready/','upwind/'].every(p=>api.MODS.some(m=>m.path===p)));}
{const {api}=boot();report('empty device: no records, no crash',api.records().length===0&&api.csvRows().length===1);}
{const {api}=boot(FIX);const R=api.records();const mods=new Set(R.map(r=>r.mod));
 report('reads records from all five modules',mods.size===5,[...mods].join(', '));
 report('every activity has a readable name (no raw ids, no blanks)',R.every(r=>r.act&&!/undefined|^[a-z]+[A-Z]?$|^tq-|^\d+$/.test(r.act)),R.map(r=>r.act).join(' | ').slice(0,160));
 const counts={};R.forEach(r=>counts[r.mod]=(counts[r.mod]||0)+1);const exp={'Charge the Line':JSON.parse(FIX['e102-pump-trainer']).log.length,'Patient Contact':JSON.parse(FIX['patient-contact']).runs.length+JSON.parse(FIX['patient-contact']).drillRuns.length,'Bleed Control':JSON.parse(FIX['bleed-control']).runs.length,'BLS Ready':JSON.parse(FIX['bls-ready']).runs.length,'Upwind':JSON.parse(FIX['upwind']).runs.length};
 report('record counts match each module exactly',Object.keys(exp).every(k=>counts[k]===exp[k]),JSON.stringify(counts));
 const rows=api.csvRows();const hdr=rows[0].join('|');report('CSV header',hdr==='Name|Organization|Module|Type|Activity|Patient|Date|Mode|Score|Instructor');
 const crew=rows.filter(r=>r[8]!==undefined&&r[9]==='Capt. Lee');report('drill-night call credits every crew member, with the instructor',crew.length===3&&new Set(crew.map(r=>r[0])).size===3,crew.map(r=>r[0]).join(', '));
 report('name and organization picked up from the modules',api.profile().name==='Max'&&api.profile().org==='Monitor Twp FD');
 report('CSV is valid (quoted, every row 10 columns)',api.toCSV(rows).split('\n').every(l=>(l.match(/","/g)||[]).length===9));
 report('rows sorted newest first',rows.slice(1).every((r,i,a)=>i===0||a[i-1][6]>=r[6]));}
{// Charge the Line data saved before the per-run log existed still shows up (best score per scenario)
 const {api}=boot({'e102-pump-trainer':JSON.stringify({name:'',scen:{'0':{level:1,best:88,runs:3,last:'2026-09-30T10:00:00Z',tier:1}},math:{}})});const R=api.records();
 report('older Charge the Line data (summary only) still appears',R.length===1&&/best of 3/.test(R[0].type)&&R[0].score===88&&R[0].act==='Residential structure fire');}
{// backup → restore on a fresh device reproduces everything
 const a=boot(FIX);const file=JSON.stringify(a.api.backup());const b=boot();const nmods=b.api.restore(JSON.parse(file));
 report('backup → restore on a new device brings back every module',nmods===5&&b.api.csvRows().length===a.api.csvRows().length,`${nmods} modules, ${b.api.csvRows().length-1} rows`);
 let threw=false;try{b.api.restore({hello:'world'});}catch(e){threw=true;}report('restore refuses a file that is not a Preconnect backup',threw);
 let threw2=false;const c=boot(FIX);try{c.api.restore({app:'preconnect',data:{'bls-ready':'{"runs":[]}','patient-contact':'{not json'}});}catch(e){threw2=true;}report('a damaged backup changes nothing at all (no half-restore)',threw2&&c.S['patient-contact']===FIX['patient-contact']&&c.S['bls-ready']===FIX['bls-ready']);}
{const P=fs.readFileSync(path.join(__dirname,'..','privacy.html'),'utf8'),F=fs.readFileSync(path.join(__dirname,'..','feedback.html'),'utf8');
 report('privacy page and feedback page exist and are linked',/href="privacy\.html"/.test(html)&&/href="feedback\.html"/.test(html)&&/never see them/.test(P)&&/preconnect-stats/.test(P)&&/Report a problem/.test(F));
 report('social preview card is set up',/og:image" content="https:\/\/[^"]+og-card\.png(\?v=\d+)?"/.test(html)&&fs.existsSync(path.join(__dirname,'..','og-card.png')));
 report('the link preview text names every module\'s subject, hazmat (Upwind) included, on every page',['index.html','privacy.html','feedback.html'].every(f=>{const h=fs.readFileSync(path.join(__dirname,'..',f),'utf8');const d=(h.match(/<meta name="description" content="([^"]+)"/)||[])[1]||'';return /pump/.test(d)&&/patient care/.test(d)&&/bleeding/.test(d)&&/BLS/.test(d)&&/hazmat/.test(d);})&&/og:description" content="[^"]*hazmat/.test(html));
 const snip=html.split('<script data-pca>')[1];report('analytics snippet present and pointed at preconnect.goatcounter.com',!!snip&&/https:\/\/preconnect\.goatcounter\.com\/count/.test(snip));
 // run the snippet in isolation: names and typed text can't survive into an event path; buckets are coarse
 const W={addEventListener(){}},sent=[];global.window=W;global.localStorage={getItem:()=>null};global.document={createElement:()=>({setAttribute(){}}),head:{appendChild(){}}};
 new Function(snip.split('</script>')[0])();W.goatcounter={count:o=>sent.push(o.path)};W.PCA.ev('bls/finish/adult/Max Tester said "hi" <b>');W.PCA.flush();
 report('event paths are cleaned to safe characters (no spaces, quotes, or tags)',/^[a-z0-9\/\-]+$/.test(sent[0]||'x '),sent[0]);
 report('scores are reported only as coarse bands',W.PCA.bkt(97)==='score-90-100'&&W.PCA.bkt(83)==='score-80s'&&W.PCA.bkt(12)==='score-under-60');}
{// Milestone 1: fonts served from this site on every root page; nothing loads from Google; every font file exists and is in the offline cache list
 const pages=['index.html','privacy.html','feedback.html'].map(f=>fs.readFileSync(path.join(__dirname,'..',f),'utf8'));const urls=[...new Set(pages.flatMap(h=>[...h.matchAll(/url\((fonts\/[^)]+)\)/g)].map(m=>m[1])))];
 report('fonts served from this site on every page, cached offline, no request to Google',pages.every(h=>!/fonts\.googleapis|gstatic\.com/.test(h)&&/@font-face/.test(h))&&urls.length>=5&&urls.every(u=>fs.existsSync(path.join(__dirname,'..',u))&&sw.includes(`'${u}'`)),`${urls.length} font files`);
 report('privacy page says nothing loads from Google',/Nothing loads from Google/.test(fs.readFileSync(path.join(__dirname,'..','privacy.html'),'utf8')));}
{// Milestone 1: install coaching. Shown to an iPhone browser, hidden once dismissed, never shown when already installed.
 const a=boot();global.navigator={userAgent:'Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) Safari/604.1'};a.api.installHint();const shown=a.els.install.hidden===false&&a.els['install-ios'].hidden===false;
 a.els['install-later'].onclick();const dismissed=a.els.install.hidden===true&&a.S['preconnect-install']==='no';a.api.installHint();const stays=a.els.install.hidden===true;
 const b=boot();global.navigator={userAgent:'iPhone',standalone:true};b.api.installHint();const installed=b.els.install.hidden===true;
 const c=boot();global.navigator={userAgent:'Mozilla/5.0 (X11; Linux) Firefox'};c.api.installHint();const other=c.els.install.hidden===true;
 report('install hint: iPhone browser sees it, dismissing hides it for good, installed or unsupported browsers never see it',shown&&dismissed&&stays&&installed&&other,`shown ${shown} dismissed ${dismissed} stays ${stays} installed ${installed} other ${other}`);}
{// Milestone 2: the Today view and module progress
 const a=boot({'bls-ready':JSON.stringify({runs:[{kind:'station',id:'adult',score:95,d:new Date().toISOString(),tier:1}]})});const T=a.api.today();a.api.render();
 report('Today view: picks up where you left off and counts this week',!!T.last&&T.last.mod==='BLS Ready'&&T.last.act==='Adult CPR and AED'&&T.last.score===95&&T.week===1&&T.mods.find(m=>m.id==='bls').done===1&&T.mods.find(m=>m.id==='bls').total===19&&/Pick up where you left off/.test(a.els.today.innerHTML)&&/bls-ready\//.test(a.els.today.innerHTML),`${T.last&&T.last.act} · week ${T.week}`);
 const b=boot(FIX);const Tb=b.api.today();report('module progress counts distinct activities, never above the total',Tb.mods.every(m=>m.done<=m.total&&(m.done>0||!b.api.records().some(r=>r.mod===m.name))),Tb.mods.map(m=>`${m.id} ${m.done}/${m.total}`).join(', '));
 const c=boot();c.api.render();report('empty device: Today view points new people at a lesson',/Start with a ten-minute lesson/.test(c.els.today.innerHTML)&&c.api.today().last===null);}
{// Milestone 2: one settings sheet, one key, applied to the page
 const a=boot();a.api.setSetting('text','large');a.api.setSetting('contrast','high');const s=a.api.settings();const de=global.document.documentElement.dataset;
 report('settings: saved under preconnect-settings and applied to the page',s.text==='large'&&s.contrast==='high'&&de.text==='large'&&de.contrast==='high'&&JSON.parse(a.S['preconnect-settings']).text==='large'&&s.haptics==='on'&&s.sound==='off',JSON.stringify(s));
 a.api.setSetting('stats','off');const off=a.S['preconnect-stats']==='off'&&a.api.settings().stats==='off';a.api.setSetting('stats','on');report('statistics switch in Settings is the same switch as the Privacy page',off&&a.api.settings().stats==='on'&&a.S['preconnect-stats']===undefined);
 const el={textContent:''};a.api.countUp(el,87);report('score count-up lands on the exact score when motion is unavailable',el.textContent==='87');
 {const core=fs.readFileSync(path.join(__dirname,'..','preconnect-core.js'),'utf8');report('motion is honored: Reduce Motion and the Motion = Off setting stop every animation (rules live in the shared core)',/prefers-reduced-motion:reduce\)\{\*\{animation:none!important/.test(core)&&/html\[data-motion="off"\] \*\{animation:none!important/.test(core));}}
{// Milestone 3: shared core (same checks every suite runs) plus the hub's Due for review cards and the cross-repo identity check
 const cp=path.join(__dirname,'..','preconnect-core.js');const ct=fs.readFileSync(cp,'utf8');const first=ct.split('\n')[0];const body=ct.slice(first.length+1);const want=(first.match(/sha256:([0-9a-f]{64})/)||[])[1];const got=require('crypto').createHash('sha256').update(body,'utf8').digest('hex');
 report('shared core loaded first, cached offline, header hash matches body',want===got&&sw.includes("'preconnect-core.js'")&&html.indexOf('<script src="preconnect-core.js"></script>')<html.indexOf('\n<script>\n'),want===got?'hash ok':`expected ${got.slice(0,12)}`);
 const sib=['charge-the-line','patient-contact','bleed-control','bls-ready'].map(r=>[r,path.join(__dirname,'..','..',r,'preconnect-core.js')]).filter(([r,f])=>fs.existsSync(f));
 if(sib.length){const drift=sib.filter(([r,f])=>fs.readFileSync(f,'utf8')!==ct).map(([r])=>r);report('shared core is byte-identical in every sibling repo checked out next to this one',drift.length===0,drift.length?'drifted: '+drift.join(', '):`${sib.length} siblings match`);}
 else report('shared core identity across repos (skipped: no sibling repos checked out)',true);
 const {boot}=require('./hub_mock.js');const {api}=boot();const d=n=>new Date(Date.now()-n*864e5).toISOString();
 const one=api.pcSpacing([{d:d(0),score:90}]),two=api.pcSpacing([{d:d(5),score:90},{d:d(4),score:90}]),miss=api.pcSpacing([{d:d(5),score:90},{d:d(1),score:40}]);
 report('spacing: 1, 3, 7, 14, 30 days after each clear at 70+; a miss resets',api.pcSpacing([]).status==='never'&&one.level===1&&one.dueIn===1&&two.level===2&&two.status==='due'&&miss.status==='missed');
 const a=boot({'bls-ready':JSON.stringify({runs:[{kind:'station',id:'adult',score:95,d:d(10),tier:1},{kind:'station',id:'tempo',score:40,d:d(2),tier:0}]})});a.api.render();const D=a.api.due();
 report('Today view: Due for review cards, most overdue first, a miss reads "try again"',D.length===2&&D[0].act==='Adult CPR and AED'&&D[0].sp.status==='due'&&D[1].sp.status==='missed'&&/Due for review/.test(a.els.today.innerHTML)&&/try again/.test(a.els.today.innerHTML),D.map(g=>g.act+' '+g.sp.status).join(', '));
 const h=a.api.pcDebriefBody({score:90,compare:a.api.pcBestPrev([{d:d(3),score:80}]),metrics:[['Rate','110']],steps:[{name:'Shock',ok:false,missed:true}]});report('debrief body renders compare line, metrics and steps tables',/Best 80 · last time 80 · new best/.test(h)&&/pc-metrics/.test(h)&&/pc-steps/.test(h));}
{// Milestone 6: sound and haptics (core). A fake AudioContext records every tone; a fake vibrate records every pattern.
 const fakeAudio=()=>{const log=[];const AC=function(){this.currentTime=0;this.state='running';this.destination={};this.resume=()=>{};this.createOscillator=()=>({type:'sine',frequency:{value:0},connect(){},start(t){log.push({f:this.frequency.value,t});},stop(){}});this.createGain=()=>({gain:{setValueAtTime(){},exponentialRampToValueAtTime(){}},connect(){}});};const buzz=[];const F={log,buzz,fs:()=>log.map(x=>x.f),arm(){global.window=global.window||{};global.window.AudioContext=AC;navigator.vibrate=p=>{buzz.push(JSON.stringify(p));return true;};}};F.arm();return F;};
 {const F=fakeAudio();const {api}=boot();F.arm();const off=api.pcCue('good');const offBuzz=api.pcBuzz('bad');api.setSetting('sound','on');const preview=F.fs().slice();api.pcCue('bad');api.pcBuzz('bad');api.setSetting('haptics','off');const nb=api.pcBuzz('bad');api.pcMetro(110);const st=api.pcMetroState();const ticks=F.fs().filter(f=>f===880).length;api.pcMetro(0);
  report('sound and haptics: silent with sound off, haptics follow their switch, turning sound on previews a tone, cues play their notes, the metronome schedules 880 Hz ticks at 110 and stops',off===false&&offBuzz===true&&F.buzz[0]==='[30,40,30]'&&preview.join()==='660,990'&&F.fs().includes(220)&&F.buzz.filter(b=>b==='[30,40,30]').length>=2&&nb===false&&!!st&&st.bpm===110&&ticks>=1&&api.pcMetroState()===null,`preview ${preview.join()}, ticks ${ticks}, buzz ${F.buzz.join(' ')}`);
  function buzz0(F){return JSON.parse(F.buzz[0]);}
  delete global.window.AudioContext;delete navigator.vibrate;}}
{// Patient Contact's new calls: pediatric breathing (0.28.0) and chest pain (0.29.0) read by name; the tile counts 19 activities
 const p=boot({'patient-contact':JSON.stringify({runs:[{call:'pd',score:95,d:new Date().toISOString(),tier:1,variant:'Croup — barking cough, stridor when upset'},{call:'cp',score:100,d:new Date().toISOString(),tier:0,variant:'Classic: pressure into his left arm and jaw, sweating · inferior STEMI'}]})});const PR=p.api.records();const PT=p.api.today().mods.find(m=>m.id==='pc');
 report('Patient Contact: the new calls read "Pediatric breathing" and "Chest pain" and the tile counts 19 activities',PR.length===2&&PR.some(r=>r.act==='Pediatric breathing')&&PR.some(r=>r.act==='Chest pain')&&PT.total===19&&PT.done===2,`${PR.map(r=>r.act).join(', ')}, total ${PT&&PT.total}`);}
{// Upwind (U0): the fifth tile, its name table, records with readable names, the instructor mark and the backup key
 const u=boot({upwind:JSON.stringify({runs:[{kind:'drill',id:'placard',score:88,d:new Date().toISOString(),tier:0},{kind:'scenario',id:'i75',score:70,d:new Date().toISOString(),tier:2,variant:'B',inst:1}]})});const UR=u.api.records();const UT=u.api.today().mods.find(m=>m.id==='uw');
 report('Upwind: tile with 19 planned activities (the Graniteville, Kingman and East Palestine Real Calls count), records read with readable names, incidents show tier, layout and the instructor mark, key is backed up',UR.length===2&&UR.some(r=>r.mod==='Upwind'&&r.type==='Drill'&&r.act==='Placard ID')&&UR.some(r=>r.type==='Incident'&&r.act==='Tanker on its side, I-75'&&r.mode==='Chaos · instructor'&&r.pat==='Layout B')&&UT.total===19&&UT.done===2&&(()=>{const g=boot({upwind:JSON.stringify({runs:[{kind:'scenario',id:'grani',score:90,d:new Date().toISOString(),tier:1}]})});const r=g.api.records()[0];return r.act==='Real Call: Graniteville, 2005'&&r.type==='Incident'&&r.pat==='';})()&&(()=>{const g=boot({upwind:JSON.stringify({runs:[{kind:'scenario',id:'king',score:100,d:new Date().toISOString(),tier:0}]})});return g.api.records()[0].act==='Real Call: Kingman, 1973';})()&&u.api.MODS.some(m=>m.key==='upwind'&&m.path==='upwind/')&&Object.keys(u.api.backup().data).includes('upwind'),UR.map(r=>r.act+' / '+r.mode).join(' | '));}
{const b=boot({'bleed-control':JSON.stringify({runs:[{kind:'scenario',id:'garage',score:80,d:new Date().toISOString(),tier:1,inst:1}]}),'bls-ready':JSON.stringify({runs:[{kind:'station',id:'adult',score:90,d:new Date().toISOString(),tier:0,inst:1,who:['Jo'],night:'x'}]})});const R=b.api.records();
 report('Bleed Control and BLS Ready instructor-injected runs read "· instructor" in Mode, and a Drill Night name still rides along',R.find(r=>r.score===80).mode==='Recall · instructor'&&R.find(r=>r.score===90).mode==='Guided · instructor'&&R.find(r=>r.score===90).who[0]==='Jo',R.map(r=>r.mode).join(' | '));}
{// Milestone 10: daylight contrast, automatic high contrast, focus outlines, landscape rules, screen-reader hooks
 {const {api,els}=boot();const css=api.PC_LOOK_CSS;api.setSetting('contrast','day');const day=document.documentElement.dataset.contrast;api.setSetting('contrast','normal');const normal=document.documentElement.dataset.contrast;
  global.matchMedia=q=>({matches:/prefers-contrast/.test(q)});api.applySettings();const auto=document.documentElement.dataset.contrast;api.setSetting('contrast','day');const dayWins=document.documentElement.dataset.contrast;delete global.matchMedia;api.setSetting('contrast','normal');
  const rec=[];els['b-msg'].setAttribute=(k,v)=>rec.push(k+'='+v);els['b-msg'].getAttribute=()=>null;api.pcA11y();
  report('accessibility: Daylight tokens, focus outlines and landscape rules live in the core; Daylight applies; a phone asking for more contrast gets High unless Daylight was chosen; feedback lines get aria-live',/data-contrast="day"\]\{--bg:#000/.test(css)&&/focus-visible\{outline:3px solid/.test(css)&&/orientation:landscape\) and \(max-height:520px\)/.test(css)&&day==='day'&&normal==='normal'&&auto==='high'&&dayWins==='day'&&rec.includes('aria-live=polite')&&html.includes('data-val="day">Daylight'),`day ${day}, auto ${auto}, a11y ${rec.join(' ')}`);}}
{// Milestone 9: the daily drill rotates across all four modules and deep-links; done-today, streak and level come from the records
 {const {api}=boot();const picks=Array.from({length:20},(_,i)=>api.dailyPick(1000+i));const ids=new Set(picks.map(p=>p.mod+':'+p.id)),mods=new Set(picks.map(p=>p.mod));const p0=api.dailyPick(1000);
  report('daily drill: twenty days give twenty different drills across all five modules, each with a readable name and a deep link into its module',ids.size===20&&mods.size===5&&picks.every(p=>p.name&&p.name!==p.id&&/\?drill=/.test(p.href)&&p.href.startsWith(api.MODS.find(m=>m.id===p.mod).path))&&api.dailyPick(1020).id===p0.id,`${picks.map(p=>p.id).join(',')}`);}
 {const d=n=>new Date(Date.now()-n*864e5).toISOString();const pick0=boot().api.dailyPick();const key={bls:'bls-ready',ctl:'e102-pump-trainer',pc:'patient-contact',bc:'bleed-control',uw:'upwind'}[pick0.mod];
  const store={'bls-ready':JSON.stringify({runs:[{kind:'station',id:'adult',score:90,d:d(0),tier:0},{kind:'station',id:'bvm',score:90,d:d(1),tier:0},{kind:'station',id:'infant',score:90,d:d(2),tier:0}]})};
  const b=boot(store);const s3=b.api.streak();const P=b.api.progression();b.api.render();const html=b.els.today.innerHTML;
  const c=boot({'bls-ready':JSON.stringify({runs:[{kind:'station',id:'adult',score:90,d:d(1),tier:0},{kind:'station',id:'bvm',score:90,d:d(2),tier:0},{kind:'station',id:'tempo',score:90,d:d(5),tier:0}]})});const s2=c.api.streak();
  const e=boot();e.api.render();const empty=e.api.progression();
  report('progression: streak counts consecutive days ending today or yesterday, level is one per eight activities, the Today view shows the daily card and the level card',s3===3&&s2===2&&P.level===1&&P.into===3&&P.next===5&&/Today's 60-second drill/.test(html)&&/data-daily="1"/.test(html)&&/Level 1 · 3-day streak/.test(html)&&/3 of \d+ activities/.test(html)&&empty.level===1&&empty.streak===0&&/Level 1<\/div>/.test(e.els.today.innerHTML),`streaks ${s3}/${s2}, level ${P.level} into ${P.into}`);
  const big=boot({'bls-ready':JSON.stringify({runs:['tempo','adult','infant','child2','bvm','chokeA','chokeI','team','opioid','baby','child','pool','crib','lesson','exam','numbers','ages'].map((id,i)=>({kind:i<13?'station':i===13?'lesson':i===14?'exam':'drill',id,score:90,d:d(0),tier:0}))})});const PB=big.api.progression();
  report('progression: seventeen activities is level 3 with one into it',PB.done===17&&PB.level===3&&PB.into===1&&PB.next===7,`done ${PB.done}, level ${PB.level}`);}
 {// done today: a Drill row from the picked module with the picked name, dated today
  const {api}=boot();const pick=api.dailyPick();const recs=[{mod:pick.module,act:pick.name,type:'Drill',d:new Date().toISOString()}],old=[{mod:pick.module,act:pick.name,type:'Drill',d:new Date(Date.now()-864e5).toISOString()}],other=[{mod:pick.module,act:'Something else',type:'Drill',d:new Date().toISOString()}];
  report('daily drill: done today only when that module\'s drill with that name was recorded today',api.dailyDone(pick,recs)===true&&api.dailyDone(pick,old)===false&&api.dailyDone(pick,other)===false&&/done/.test((()=>{const b=boot();return b.api.dailyHTML(b.api.today());})())===false);}}
{// Milestone 7: Drill Night session (core) and the hub's board
 {const {api}=boot();api.pcDrillStart(' Max ',['Jo','Sam','Jo','',' Sam '],'MTFD');const d=api.pcDrill();api.pcDrillWho('Sam');const run=api.pcDrillStamp({score:90});api.pcDrillWho(' Lee ');const d2=api.pcDrill();api.pcDrillEnd();const after=api.pcDrillRaw();
  report('Drill Night session: names trimmed and deduplicated, who stamps runs with the instructor and the night, a new name joins the roster, ending keeps the roster',d.inst==='Max'&&d.org==='MTFD'&&d.roster.join()==='Jo,Sam'&&run.who[0]==='Sam'&&run.inst==='Max'&&run.night===d.start&&d2.who==='Lee'&&d2.roster.join()==='Jo,Sam,Lee'&&api.pcDrill()===null&&after.roster.join()==='Jo,Sam,Lee'&&api.pcDrillStamp({score:1}).who===undefined,`roster ${d.roster.join()} → ${after.roster.join()}`);}
 {const start=new Date(Date.now()-3600e3).toISOString();const now=new Date().toISOString();
  const b=boot({'preconnect-drill':JSON.stringify({on:true,inst:'Max',org:'MTFD',roster:['Jo','Sam','O"Neil <b>'],who:'Jo',start}),
    'bls-ready':JSON.stringify({runs:[{kind:'station',id:'adult',score:88,d:now,tier:0,who:['Jo'],inst:'Max',night:start},{kind:'station',id:'adult',score:70,d:now,tier:1}]}),
    'bleed-control':JSON.stringify({runs:[{kind:'scenario',id:'kitchen',score:95,d:now,tier:0,who:['Sam'],inst:'Max',night:start}]}),
    'e102-pump-trainer':JSON.stringify({scen:{},log:[{i:0,score:91,tier:0,d:now,v:'A',who:['Jo'],inst:'Max',night:start}],extra:[]})});
  const T=b.api.tonight();b.api.render();const card=b.els.drillcard.innerHTML;b.api.drillOpen();const board=b.els.drillbox.innerHTML;const csv=b.api.toCSV(b.api.csvRows(T));b.api.pcDrillPick();const pick=b.els['pc-drillbox'].innerHTML;b.api.pcDrillBar();const bar=b.els['pc-drill'].innerHTML;
  report('Drill Night board: tonight = runs stamped with this night only, card counts runs and people, board lists the roster with bests and tonight\'s runs, CSV has one row per person with the instructor',T.length===3&&/3 runs tonight · 2 of 3 on the board · up now: Jo/.test(card)&&/Jo <span class="chip">up<\/span><\/td><td>2 runs · best 91/.test(board)&&/Sam<\/td><td>1 run · best 95/.test(board)&&/Adult CPR and AED/.test(board)&&csv.split('\n').length===4&&/"Jo","MTFD".*"Max"/.test(csv)===false&&/"Jo",.*,"Max"$/m.test(csv)&&/"Sam",/.test(csv),`${T.length} tonight; csv ${csv.split('\n').length} lines`);
  report('Drill Night picker and bar: names escaped (a quote or a tag in a name cannot break the button), current person marked, bar shows who is up',/data-n="O&quot;Neil &lt;b&gt;"/.test(pick)&&/class="pc-drill-name on" data-drill="who" data-n="Jo"/.test(pick)&&/Up: Jo/.test(bar)&&/data-drill="pick"/.test(bar));
  b.api.pcDrillAct('who',{dataset:{n:'Sam'}});const sw=b.api.pcDrill().who;b.api.drillOpen();b.els['d-end'].onclick();const stillOn=!!b.api.pcDrill();b.els['d-end'].onclick();b.api.render();
  report('Drill Night: switching who, ending takes two taps, after the end the card offers set-up again and the roster is kept',sw==='Sam'&&stillOn&&b.api.pcDrill()===null&&/Set up Drill Night/.test(b.els.drillcard.innerHTML)&&b.api.pcDrillRaw().roster.length===3&&/Drill Night ended: 3 runs/.test(b.els['b-msg'].textContent));}
 {const b=boot();b.api.render();b.els['d-setup'].onclick();b.els['d-inst'].value='Max';b.els['d-org'].value='';b.els['d-roster'].value='Jo\nSam\n\nJo';b.els['d-start'].onclick();const d=b.api.pcDrill();
  report('Drill Night set-up: instructor and roster from the form, the picker opens right away, the setup card becomes the live card',!!d&&d.inst==='Max'&&d.roster.join()==='Jo,Sam'&&d.who===''&&/Who's up\?/.test(b.els['pc-drillbox'].innerHTML)&&/Drill Night in progress/.test(b.els.drillcard.innerHTML));}}
{// Milestone 5: Charge the Line's lesson and drills show up with readable names and count toward its total
 {const c=boot({'e102-pump-trainer':JSON.stringify({name:'',scen:{},log:[{i:0,score:88,tier:1,d:new Date().toISOString(),v:'B',inst:1},{i:1,score:70,tier:0,d:new Date().toISOString()}]})});const R=c.api.records();const r0=R.find(r=>r.score===88),r1=R.find(r=>r.score===70);
  report('Charge the Line layout and instructor runs show in the record (Patient column = layout, Mode notes instructor)',r0&&r0.pat==='Layout B'&&r0.mode==='Recall · instructor'&&r1&&r1.pat===''&&r1.mode==='Guided',`${r0&&r0.pat} / ${r0&&r0.mode}`);}
 const a=boot({'e102-pump-trainer':JSON.stringify({name:'',scen:{},log:[],extra:[{kind:'lesson',id:'lesson',score:92,d:new Date().toISOString()},{kind:'drill',id:'friction',score:75,d:new Date().toISOString()}]})});const R=a.api.records();const T=a.api.today();
 report('Charge the Line lessons and drills appear in the record with readable names and count toward the module total',R.length===2&&R.some(r=>r.type==='Lesson'&&r.act==='Pump operations lesson'&&r.score===92)&&R.some(r=>r.type==='Drill'&&r.act==='Friction loss')&&T.mods.find(m=>m.id==='ctl').done===2&&T.mods.find(m=>m.id==='ctl').total===15,R.map(r=>r.type+': '+r.act).join(', '));}
report('trademark notices for both certifying organizations',/STOP THE BLEED® is a registered trademark/.test(html)&&/trademarks of the American Heart Association/.test(html));
console.log(`\n${n-failed}/${n} checks passed`);process.exit(failed?1:0);
